#!/bin/bash
#
# Tests and builds project documentation.
#
# Usage:
#       scripts/doc <options>
#
# Options:
#       --open    Open documentation after building

set -e

if ! command -v cargo-deadlinks &> /dev/null; then
  cargo install cargo-deadlinks
fi

ARGS=("--document-private-items" "--no-deps")
if [ "$1" = "--open" ]; then
  ARGS+=("--open")
fi

ALL_RUST_FILES=($(find . -type f -name "*.rs" -print))

# Validate all link references exist
scripts/_scripts/markdown/validate-link-refs.js '((?:^\s*(?:\/\/[\/|!]?).*$[\r]?\n)+)' '^\s*(?:\/\/[\/|!]?)' ${ALL_RUST_FILES[@]}

cargo doc ${ARGS[@]}

if rustc -V | grep -q "nightly"; then
  # Validate links are valid. Only nightly supports intra-doc links, so guard on
  # that until https://github.com/rust-lang/rfcs/pull/1946 is stabilized.
  cargo deadlinks --check-http
fi
