#!/bin/bash
#
# Publishes a slide release. Intended to be used in Travis deployment.
#
# Usage:
#       scripts/publish

VERSION_REGEX="version = \"([0-9]+\.[0-9]+\.[0-9]+)\""
[[ "$(cat libslide/Cargo.toml)" =~ $VERSION_REGEX ]]
LIBSLIDE_VERSION="${BASH_REMATCH[1]}"
echo "libslide version - $LIBSLIDE_VERSION"

pushd libslide
cargo publish --token="$CARGO_DEPLOY_TOKEN" || true
popd

pushd slide
sed -i "s/libslide.*/libslide = \"$LIBSLIDE_VERSION\"/g" Cargo.toml
cargo publish --allow-dirty --token="$CARGO_DEPLOY_TOKEN" || true
popd
